### ISSUE TITLE
macOS Big Sur can't open wallet.

### ISSUE THREAD

**Issue by bluemonkey96** [kryptokrona/kryptokrona-desktop-wallet#33]
I'm trying to open the wallet on my MacBook.
MacBook Air (M1, 2020)
macOS Big Sur 11.5.1 (20G80)

this is what I am greeted with...
<img width="258" alt="Screenshot 2022-07-30 at 21 22 29" src="https://user-images.githubusercontent.com/76632691/181953224-ce11189f-a283-479c-a013-fd6dfc04de0f.png">

extra info:
<img width="258" alt="Screenshot 2022-07-30 at 21 24 53" src="https://user-images.githubusercontent.com/76632691/181958207-39392d53-8aaa-4834-9858-5b3ea8c4078d.png">

**Comment by f-r00t** [comment]
https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/12.0/mac/12.0

Follow these instruction on how to open apps from unidentified developers.

**Comment by bluemonkey96** [comment]
this is not "complete" 👎 
<img width="654" alt="Screenshot 2022-07-31 at 15 59 52" src="https://user-images.githubusercontent.com/76632691/182029875-1feacbd5-336c-42b8-899e-bf40031cbafa.png">

funny how you marked this as completed without checking if it was completed :)
