### ISSUE TITLE
macOS Big Sur can't open wallet.

### ISSUE THREAD

**Issue by bluemonkey96** [kryptokrona/kryptokrona-desktop-wallet#34]
I'm trying to open the wallet on my MacBook.
MacBook Air (M1, 2020)
macOS Big Sur 11.5.1 (20G80)

this is what I am greeted with...
<img width="258" alt="Screenshot 2022-07-30 at 21 22 29" src="https://user-images.githubusercontent.com/76632691/181953224-ce11189f-a283-479c-a013-fd6dfc04de0f.png">

extra info:
<img width="258" alt="Screenshot 2022-07-30 at 21 24 53" src="https://user-images.githubusercontent.com/76632691/181958207-39392d53-8aaa-4834-9858-5b3ea8c4078d.png">

<img width="654" alt="Screenshot 2022-07-31 at 15 59 52" src="https://user-images.githubusercontent.com/76632691/182029875-1feacbd5-336c-42b8-899e-bf40031cbafa.png">

This is a repost due to someone marking my previous post complete without a lack of knowledge.

**Comment by bluemonkey96** [comment]
https://user-images.githubusercontent.com/76632691/182030634-bf278d6e-96dc-4d28-85ad-4ca32b1d6fd4.mov

https://user-images.githubusercontent.com/76632691/182031623-b7919da3-e80f-4379-aaa7-37de475227ea.mov

**Comment by bluemonkey96** [comment]
https://user-images.githubusercontent.com/76632691/182032776-67965b20-e893-40b8-be44-fb4f24104bfc.mp4

**Comment by f-r00t** [comment]
Solved. Mac users make sure to download the .dmg-file.
