### ISSUE TITLE
Försvunna miljoner

### ISSUE THREAD

**Issue by TechyGuy17** [kryptokrona/kryptokrona-desktop-wallet#6]
Helt plötsligt var jag nere på 7 miljoner från MYCKET mer, vet inte vad som hände (Är just nu inne i processen att om installera walleten och om synca från block 1, vet inte om det kommer funka)
- Version used : 0.04
- Operating System and version : Win 10 64bit

**Comment by f-r00t** [comment]
Antagligen har din lokala data blivit korrumperad på något sätt. Testa att avinstallera och ta bort protonwallet-mappen i AppData-mappen om du använder Windows (eller ~/.protonwallet på linux/mac). Du kommer till AppData-mappen så här:

_Open File Explorer/Windows Explorer
Type %AppData% into the address bar and hit enter
Navigate to the required folder (Roaming or Local)_

Sen kan du installera igen och importera med private keys/mnemonic seed.

Svara gärna om det löser problemet.

**Comment by TechyGuy17** [comment]
Tack för hjälpen men min lösning räckte! Tror bara walleten hade f:at upp något
